platform :ios, '11.0'

use_frameworks!

target 'ZiggeoDemo' do

  target 'BroadcastExtension' do
    inherit! :search_paths
  end
  
  pod 'ZiggeoMediaSDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git', :branch => 'blurring'

  pod 'ActiveLabel'
  pod 'SideMenu'
  pod 'SVProgressHUD'
  pod 'PINRemoteImage'
  pod 'IQKeyboardManagerSwift'

end
