# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TestApp' do
  
  # Pods for AdvancedTestApp
  pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git', :branch => '1.1.36-no-blurring'

end
