# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TestApp' do
  
  # Pods for AdvancedTestApp
  pod 'iOS-Client-SDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git'

end
