# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TestApp' do
  
  # Pods for AdvancedTestApp
  pod 'ZiggeoMediaSDK', :git => 'https://github.com/Ziggeo/iOS-Client-SDK.git', :branch => 'blurring'

end
